### ISSUE TITLE
Venue Test data is wrong

### ISSUE THREAD

**Issue by hoyeol** [mattupstate/spring-social-foursquare#2]
I saw the VenueTemplate and there Testcase (VenueTemplateTest class)

there Test use "venue-search.json" file located on your src/test/java/org.springframework.social.foursquare.api.impl.testdata

but it's wrong test data. I guess all test data format has problem like this?
problem is. testdata (JSON) files does not containing "notification" object.

below is correct data format example of foursquare api response

{
   meta: {
      code: 200
   },
   notifications: [
      {
         type: "notificationTray",
         item: {
         unreadCount: 0
         }
      },
   ],
   response: {
      ...
   }
}

there "notifications" with JsonToken.END_OBJECT will be exit the loop (AbstractFoursquareDeserializer class methods)

I edit temporary loop condition jp.nextToken() != JsonToken.END_OBJECT to jp.nextToken() != null . 
but maybe you will improve much than i do.

**Comment by mattupstate** [comment]
Fixed in latest commit
