### ISSUE TITLE
Venue Location Mapping wrong

### ISSUE THREAD

**Issue by hoyeol** [mattupstate/spring-social-foursquare#3]
see that https://api.foursquare.com/v2/venues/VENUE_ID TestCase.
following VenueTemplateTest only test there assertEquals Venue ID.

i wonder why didn't make test for all fields...

anyway, there latitude, longitude field doesn't mapping from json. (org.springframework.social.foursquare.api.Location)

**Comment by mattupstate** [comment]
Was a typo in the JSON mixin. Should be good to go now.
