### ISSUE TITLE
FoursquareErrorHandler need improve there functionality

### ISSUE THREAD

**Issue by hoyeol** [mattupstate/spring-social-foursquare#6]
hiya. there org.springframework.social.foursquare.api.impl.FoursquareErrorHandler class need improve there functionality.

i think there FoursquareErrorHandler will throw Exception likes FacebookErrorHandler / TwitterErrorHandler from spring-social-facebook / spring-social-twitter.

following "SocialException" hierarchy on spring-social. (SocialException - ApiException - rest of there exceptions..)

as you know https://developer.foursquare.com/docs/overview.html Errors Section describe about error

**Comment by mattupstate** [comment]
Added rudimentary error handling improvements in 1.0.5.RELEASE
