### ISSUE TITLE
User info not available in checkinOperations().getRecent

### ISSUE THREAD

**Issue by mikeybar** [mattupstate/spring-social-foursquare#7]
Hi,

have found an issue in api - i think

The recent checkin information does not get the info of the friend/user that made the checkin. 

Currently it just gives me a list of List<Checkins>  which do not contain any friend info

According to the foursquare explorer the friend info for each recent checkin should be available :

{
meta: {
code: 200
}
notifications: [
{
type: "notificationTray"
item: {
unreadCount: 2
}
}
]
response: {
recent: [
{
id: "4ebc4d134690027019bdbca2"
createdAt: 1320963347
type: "checkin"
timeZone: "Europe/Paris"

user: {
id: "15547211"
firstName: "Αα δεν θέλάτι"
lastName: "λώματός"
photo: "https://img-s.foursquare.com/userpix_thumbs/DVN4TFVXJDMKQAIK.jpg"
gender: "male"
homeCity: "Paris"
relationship: "friend"
}

venue: {
id: "4ade0d62f964a520446b21e3"
name:
contact: {
phone: "3225424242"
formattedPhone: "02 542 42 42"
}
location: {
address: "xxxxxx"
lat: 50.832266
lng: 4.35773
postalCode: "1060"
city: "yyyyy"
state: "xxxxxxxx"
}
categories: [
{
id: "4bf58dd8d48r88d1fa931735"
name: "Hotel"
pluralName: "Hotels"
shortName: "Hotel"
icon: {
prefix: "https://foursquare.com/img/categories/travel/hotel_"
sizes: [
32
44
64
88
256
]
name: ".png"
}
primary: true
}
]
verified: false
stats: {
checkinsCount: 880
usersCount: 417
tipCount: 10
}
}
source: {
name: "foursquare for iPhone"
url: "https://foursquare.com/download/#/iphone"
}
photos: {
count: 0
items: [ ]
}
comments: {
count: 0
items: [ ]
}
}

would be great if this was implemented
thanks!

**Comment by mattupstate** [comment]
I'm going to need more specific information regarding this issue. Perhaps data that shows xactly what you're receiving form the API call and not data form Foursquare's API explorer. There is nothing that indicates a problem here and my tests show otherwise.

**Comment by mikeybar** [comment]
Hi ,
theres no error or problem as such. It just that (in my opinion) there should be more info available in the Checkin objs that the getRecent() call returns. I would have thought that each Checkin obj should contain an embedded user obj (i.e. the friend user) that made the recent checkin ?  or have I totally got it wrong ?
