### ISSUE TITLE
 java.io.IOException: Attempted read from closed stream

### ISSUE THREAD

**Issue by drei01** [mattupstate/spring-social-foursquare#8]
I am authenticating Foursquare users using 

`````` buildAuthenticateUrl```
exchanging this for an access token successfully using 
```exchangeForAccess``` 
and creating a new foursquare template 
```FoursquareTemplate foursquare = new FoursquareTemplate(Constants.FOURSQUARE_API_KEY, Constants.FOURSQUARE_API_SECRET, accessGrant.getAccessToken());```

This all works fine but when i call ```foursquare.userOperations().getUser();``` I get the following exception.

```org.springframework.web.client.ResourceAccessException: I/O error: Attempted read from closed stream.; nested exception is java.io.IOException: Attempted read from closed stream.
    at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:453)
    at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:415)
    at org.springframework.web.client.RestTemplate.getForObject(RestTemplate.java:213)
    at org.springframework.social.foursquare.api.impl.AbstractFoursquareOperations.get(AbstractFoursquareOperations.java:24)```

I can debug through and get the url that the method is calling and paste it into a browser and it works fine. The bug seems to be in the spring RestTemplate but I was wondering if you could shed any light on this and it seems foursquare specific as the FacebookTemplate and TwitterTemplate both work fine.

Great work on the library by the way!

``````

**Comment by mattupstate** [comment]
I've never used the `buildAuthenticateUrl` or `exchangeForAccess` methods manually so I'm not exactly sure what might be causing this problem. I will,  however, look into it as soon as I get a chance.

**Comment by drei01** [comment]
Thanks Matt. Both those calls work for me. It's just the /user/self call that isn't working at the moment.

I am calling the url manually at the moment and using an object mapper to map to your java classes and that is working fine. 

I can post my code if you need it?

**Comment by mattupstate** [comment]
I'm more curious about debugging the HTTP request, but code would be good as well. Do you have a report from an HTTP debugger like Charles?

**Comment by drei01** [comment]
```String userSelfUrl = "https://api.foursquare.com/v2/users/self?oauth_token="+accessGrant.getAccessToken()+"&v="+DateFormatUtils.format(new Date(), "ddMMyyyy");
            HttpClient httpClient = new DefaultHttpClient();
            HttpGet httpGet = new HttpGet(userSelfUrl);
            ResponseHandler<String> responseHandler = new BasicResponseHandler();
            String response = httpClient.execute(httpGet, responseHandler);

``````
        ObjectMapper mapper = new ObjectMapper();

        FoursquareUserContainer foursquareUserContainer  = mapper.readValue(response, FoursquareUserContainer.class);
        FoursquareUser foursquareUser = foursquareUserContainer.getUser();```
``````

That is what i've got for getting the foursquare user object

I hope it helps.

I don't have an http debugger report and I don't have time to get one at the moment but I will endeavor to as soon as I can if this will be a help to you.

**Comment by paulk2media** [comment]
So, I think I found the issue to this problem (after searching for a couple of days). It seems that the FoursquareErrorHandler class, when it calls:

String content = readFully(response.getBody());     

The readFully ends up causing the ContentLengthInputStream to close its underlying stream. Then, once the stream is closed, subsequent calls to read the data fail due to the stream already being closed.

To temporarily work around this issue, I commented out the last two lines of the method:

```
public boolean hasError(ClientHttpResponse response) throws IOException
```

Hope this helps!

Thanks,

Paul

**Comment by mattupstate** [comment]
I'm not sure this exactly fixes your problem. I took this technique from the spring-social-facebook project [error handler](https://github.com/SpringSource/spring-social-facebook/blob/master/spring-social-facebook/src/main/java/org/springframework/social/facebook/api/impl/FacebookErrorHandler.java). You can see the same code exists in this project.

**Comment by drei01** [comment]
It does certainly look like it is the foursquareerrorhandler that is causing the problem. I have implemented the same technique in a project of my own and it has also caused the same error there.

**Comment by mattupstate** [comment]
Have you tried a more recent version? I've made a few changes lately.

**Comment by drei01** [comment]
I used this as the template:
https://github.com/mattupstate/spring-social-foursquare/blob/master/spring-social-foursquare/src/main/java/org/springframework/social/foursquare/api/impl/FoursquareErrorHandler.java

**Comment by mattupstate** [comment]
That functionality is dependent on configuration that happens in `FoursquareTemplate` ([view file](https://github.com/mattupstate/spring-social-foursquare/blob/master/spring-social-foursquare/src/main/java/org/springframework/social/foursquare/api/impl/FoursquareTemplate.java)). I can't really support your problem if you're not using the library as is.

More specifically, checkout the `setRequestFactory` method and the comment within it.

**Comment by drei01** [comment]
thanks, I will take a look at that. I am using the library as is. I am also using some of the techniques you have used in my own library.

**Comment by nowheresly** [comment]
You should try to use a spring BufferingClientHttpRequestFactory
template.setRequestFactory(new BufferingClientHttpRequestFactory(template.getRequestFactory()));
see :
http://stackoverflow.com/questions/13182519/spring-rest-template-usage-causes-eofexception
